- name: Deploy to EC2
  hosts: localhost
  connection: local
  vars:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    aws_session_token: "{{ lookup('env', 'AWS_SESSION_TOKEN') }}"

  tasks:
    - name: Launch EC2 Instance
      ec2_instance:
        instance_type: t3.medium
        image_id: ami-051f8a213df8bc089
        region: us-east-1
        key_name: test
        vpc_subnet_id: subnet-09673e61364597e15
        tags:
          Name: Eshop
        count: 1
        security_group: eshop
        network:
          assign_public_ip: yes
        wait: yes
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ aws_session_token }}"
      register: ec2_instance_result

    - name: Add instance host to group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: launched
      loop: "{{ ec2_instance_result.instances }}"

    - name: Wait for SSH connection
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
        timeout: 300
      loop: "{{ ec2_instance_result.instances }}"

- name: Configure EC2 Instances
  hosts: launched
  connection: ssh
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/runner/.ssh/test.pem
  tasks:
    - name: Install Git and Docker
      yum:
        name:
          - git
          - docker
        state: latest
        update_cache: yes
    - service:
        name: docker
        state: started
        enabled: yes
    - name: Set proper rights to Docker service
      shell: usermod -a -G docker ec2-user

    - name: Fetch eshop from Git
      git:
        repo: "https://github.com/omaj01/4IT572_eshop_omaj01.git"
        dest: ./app

    - name: Build Eshop Docker image
      docker_image:
        build:
          path: ./app
        name: eshop
        tag: latest
        source: build
    - name: Run Eshop Docker
      docker_container:
        name: eshop
        image: eshop
        state: started
        ports:
          - "80:3000"

    - name: Wait for eshop to run
      wait_for:
        port:
          80
