name: Build and tests eshop
on:
  workflow_dispatch:
  pull_request:
      branches:
        - main

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 14

      - name: Cache
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install packages with npm
        run: |
          npm ci

  Build:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 14

      - name: Cache
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build -- --colors

      - name: Cache node modules and build folder
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/cache@v4.0.2
        with:
          path:  |
            ~/.npm
            ./node_modules
            ./build
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-build-${{ github.run_id }}

  Test:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 14

      - name: Cache
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run tests
        run: |
          npm run test -- --colors

  Deploy:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install ansible boto boto3

      - name: Setup SSH Key
        run: |
          mkdir -p /home/runner/.ssh
          echo -e "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/test.pem
          chmod 600 /home/runner/.ssh/test.pem
          ssh -i "/home/runner/.ssh/test.pem" ec2-user@ec2-54-158-238-24.compute-1.amazonaws.com
          mkdir -p testSpojeni

      - name: Setup Ansible
        uses: dawidd6/action-ansible-playbook@v2.8.0
        with:
          playbook: 'ansible/ansible.yml'
          key: '/home/runner/.ssh/test.pem'
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_PRIVATE_KEY_FILE: '/home/runner/.ssh/test.pem'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
